### PR TITLE
Enable ossec inspection

### PR DESCRIPTION
**Pull request by susiecoleman**

### CODE REVIEW

**Comment by danmassie** [comment]
I'm not sure this is necessary. @markjamesbutler and I previously decided to only enable this on the publicly available identity applications. Has the thinking changed?

**Comment by markjamesbutler** [comment]
Yup, Dave Boxall (info sec) wanted this to be applied on the API also so he
can look for internal attacks.

On 1 December 2015 at 10:50, Dan Massie <notifications@github.com> wrote:

> I'm not sure this is necessary. @markjamesbutler
> <https://github.com/markjamesbutler> and I previously decided to only
> enable this on the publicly available identity applications. Has the
> thinking changed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/identity-admin-api/pull/46#issuecomment-160932756>
> .
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by adamnfish** [comment]
[Here is an example](https://github.com/guardian/janus/blob/master/cloudformation/yaml/janus.template.yaml#L173-L183) of how to add it to your cloudformation if that's useful? There's a central bucket for the logs to go into in the infosec account now.

**Comment by susiecoleman** [comment]
@adamnfish I don't think I have permission to view that particular repo...

**Comment by danmassie** [comment]
@susiecoleman the code Adam linked to is what I based the other CF templates on, so yours is the same.

:+1:

**Pull request merged**
